
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Redux/provider";
import { Nunito } from 'next/font/google';
import { Toaster } from "sonner";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['700'], // Sélectionnez les poids nécessaires
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
